export const data = {
  loginuser: {
    _id: "1",
    preferredname: "Samy",
    firstname: "Samy",
    lastname: "Cotton",
    nationality: "American",
    dateofbirth: "05-May-1990",
    gender: "Male",
    bloodgroup: "A+",
    category: "employee",
    image: "/images/avatar1.png",
    Phonenumber: "123456789",
    Personalemail: "samycotton@example.com",
    secondarynumber: "123456789",
    website: "www.example.com",
    linkedin: "#samycotton",
    sign: false,
  },
  payment: {
    startdate: "06-Jun-2017",
    visaexpirydate: "06-Jun-2020",
  },
  employees: [
    {
      _id: "1",
      preferredname: "Samy",
      joptitle: "PHP Developer",
      Personalemail: "samycotton@example.com",
      image: "/images/personimg2.jpg",
    },
    {
      _id: "2",
      preferredname: "Maria",
      joptitle: "Designer",
      Personalemail: "mariaward@example.com",
      image: "/images/personimg1.jpg",
    },
    {
      _id: "3",
      preferredname: "Linda",
      joptitle: "IOS Developer",
      Personalemail: "lindacarver@example.com",
      image: "/images/personimg3.jpg",
    },
    {
      _id: "4",
      preferredname: "Jory",
      joptitle: "Android Developer",
      Personalemail: "jorysims@example.com",
      image: "/images/personimg4.jpg",
    },
    {
      _id: "5",
      preferredname: "Johan",
      joptitle: "Business Developer",
      Personalemail: "johansarj@example.com",
      image: "/images/personimg5.jpg",
    },
    {
      _id: "6",
      preferredname: "Sara",
      joptitle: "Tester",
      Personalemail: "saraKa@example.com",
      image: "/images/personimg6.jpg",
    },
  ],
  leavestutas: [
    {
      _id: "6",
      preferredname: "Sara",
      image: "/images/personimg6.jpg",
      leavetype: "Parental Leave",
      from: "05 Dec 2019",
      to: "07 Dec 2019",
      note: "Parenting Leave",
      stutas: "Approved",
    },

    {
      _id: "5",
      preferredname: "Johan",
      image: "/images/personimg5.jpg",
      leavetype: "Parental Leave",
      from: "02 Dec 2019",
      to: "05 Dec 2019",
      note: "Parenting Leave",
      stutas: "Pending",
    },
  ],
};
